// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVwvAgiK0jnoaQ2Zgwvk-GabdrL9KsrX4',
    appId: '1:367716780582:web:1f461d26cc1ef3749f74e7',
    messagingSenderId: '367716780582',
    projectId: 'crud-f0df5',
    authDomain: 'crud-f0df5.firebaseapp.com',
    storageBucket: 'crud-f0df5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5aoxR_I95Qwtxgv-ha6S4nbJXeNzNR0w',
    appId: '1:367716780582:android:e1e93c08d22ae1999f74e7',
    messagingSenderId: '367716780582',
    projectId: 'crud-f0df5',
    storageBucket: 'crud-f0df5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBegbZmNkLOC2UzqP5cElZKjpvQHInvAo4',
    appId: '1:367716780582:ios:de2a3339237974a09f74e7',
    messagingSenderId: '367716780582',
    projectId: 'crud-f0df5',
    storageBucket: 'crud-f0df5.firebasestorage.app',
    iosBundleId: 'com.flit.crud',
  );
}
